package filter

import "strings"

func IsGeneratedText(content string) bool {
	preview := firstLines(strings.ToLower(content), 12)
	if preview == "" {
		return false
	}

	switch {
	case strings.Contains(preview, "@generated"):
		return true
	case strings.Contains(preview, "code generated") && strings.Contains(preview, "do not edit"):
		return true
	case strings.Contains(preview, "automatically generated"):
		return true
	case strings.Contains(preview, "generated by") && strings.Contains(preview, "do not edit"):
		return true
	default:
		return false
	}
}

func IsMinifiedText(name, content string, totalLines int) bool {
	lowerName := strings.ToLower(strings.TrimSpace(name))
	if strings.Contains(lowerName, ".min.") && len(content) >= 512 {
		return true
	}

	if totalLines <= 0 || totalLines > 3 || len(content) < 2048 {
		return false
	}

	maxLineLength := 0
	for line := range strings.SplitSeq(content, "\n") {
		if len(line) > maxLineLength {
			maxLineLength = len(line)
		}
	}

	averageLineLength := len(content)
	if totalLines > 0 {
		averageLineLength = len(content) / totalLines
	}

	return maxLineLength >= 800 && averageLineLength >= 300
}

func IsLowValueArtifact(name string) bool {
	lower := strings.ToLower(strings.TrimSpace(name))
	switch lower {
	case ".gitkeep", ".keep", ".keepme", ".placeholder":
		return true
	}

	for _, suffix := range []string{"~", ".log", ".tmp", ".cache", ".pid", ".stackdump", ".swp", ".swo", ".bak", ".orig", ".rej"} {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return false
}

func firstLines(content string, limit int) string {
	if limit <= 0 || content == "" {
		return ""
	}
	lines := strings.Split(content, "\n")
	if len(lines) > limit {
		lines = lines[:limit]
	}
	return strings.Join(lines, "\n")
}
