package filter

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSkipDirectoryIgnoresConfiguredAbsolutePath(t *testing.T) {
	homeDir := t.TempDir()
	t.Setenv("HOME", homeDir)

	trashPath := filepath.Join(homeDir, ".Trash")
	if skip, reason := SkipDirectory(trashPath, ".Trash", true); !skip || reason != "ignored directory path" {
		t.Fatalf("expected configured absolute path to be skipped, got skip=%v reason=%q", skip, reason)
	}
}

func TestSkipDirectoryIgnoresConfiguredAbsoluteSubtree(t *testing.T) {
	homeDir := t.TempDir()
	t.Setenv("HOME", homeDir)

	moduleCachePath := filepath.Join(homeDir, "go", "pkg", "mod", "example.com", "mod@v1.0.0")
	if skip, reason := SkipDirectory(moduleCachePath, "mod@v1.0.0", true); !skip || reason != "ignored directory path" {
		t.Fatalf("expected configured subtree to be skipped, got skip=%v reason=%q", skip, reason)
	}
}

func TestHandleWalkErrorSkipsPermissionDenied(t *testing.T) {
	if got := HandleWalkError("/restricted", fs.ErrPermission); !errors.Is(got, filepath.SkipDir) {
		t.Fatalf("expected SkipDir for fs.ErrPermission, got %v", got)
	}
	if got := HandleWalkError("/restricted", os.ErrPermission); !errors.Is(got, filepath.SkipDir) {
		t.Fatalf("expected SkipDir for os.ErrPermission, got %v", got)
	}
}

func TestSkipDirectoryRecognizesRustBuildAndCacheDirectories(t *testing.T) {
	targetPath := filepath.Join(t.TempDir(), "project", "target")
	if skip, reason := SkipDirectory(targetPath, "target", true); !skip || reason != "rust build directory" {
		t.Fatalf("expected rust target directory to be skipped, got skip=%v reason=%q", skip, reason)
	}

	cargoRegistryPath := filepath.Join(t.TempDir(), "project", ".cargo", "registry", "index")
	if skip, reason := SkipDirectory(cargoRegistryPath, "registry", true); !skip || reason != "rust cargo registry cache" {
		t.Fatalf("expected cargo registry cache to be skipped, got skip=%v reason=%q", skip, reason)
	}
}

func TestWalkerHonorsRootGitIgnoreAndCtxIgnoreOverride(t *testing.T) {
	root := t.TempDir()
	writeFilterFile(t, filepath.Join(root, ".gitignore"), "*.txt\n")
	writeFilterFile(t, filepath.Join(root, ".ctxignore"), "!keep.txt\n")

	walker, err := NewWalker(root, true, "dump")
	if err != nil {
		t.Fatalf("NewWalker returned error: %v", err)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "ignored.txt"), "ignored.txt", "ignored.txt"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if !skip || reason != "ignored by .gitignore" {
		t.Fatalf("expected ignored.txt to be skipped by .gitignore, got skip=%v reason=%q", skip, reason)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "keep.txt"), "keep.txt", "keep.txt"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if skip {
		t.Fatalf("expected keep.txt to be unignored by .ctxignore, got reason=%q", reason)
	}
}

func TestWalkerHonorsNestedIgnoreFiles(t *testing.T) {
	root := t.TempDir()
	writeFilterFile(t, filepath.Join(root, "pkg", ".gitignore"), "generated.go\n")

	walker, err := NewWalker(root, true, "dump")
	if err != nil {
		t.Fatalf("NewWalker returned error: %v", err)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "pkg", "generated.go"), "pkg/generated.go", "generated.go"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if !skip || reason != "ignored by .gitignore" {
		t.Fatalf("expected nested generated.go to be skipped, got skip=%v reason=%q", skip, reason)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "generated.go"), "generated.go", "generated.go"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if skip {
		t.Fatalf("did not expect root generated.go to be skipped by nested ignore, got reason=%q", reason)
	}
}

func TestWalkerHonorsCtxConfigIncludeAndExcludePaths(t *testing.T) {
	root := t.TempDir()
	writeFilterFile(t, filepath.Join(root, ".ctxconfig"), `
[index]
exclude_paths = generated/**
include_paths = generated/keep.txt
`)

	walker, err := NewWalker(root, false, "index")
	if err != nil {
		t.Fatalf("NewWalker returned error: %v", err)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "generated", "out.txt"), "generated/out.txt", "out.txt"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if !skip || reason != "ignored by .ctxconfig [index]" {
		t.Fatalf("expected generated/out.txt to be skipped by .ctxconfig profile, got skip=%v reason=%q", skip, reason)
	}

	if skip, reason, err := walker.ShouldSkipFile(filepath.Join(root, "generated", "keep.txt"), "generated/keep.txt", "keep.txt"); err != nil {
		t.Fatalf("ShouldSkipFile returned error: %v", err)
	} else if skip {
		t.Fatalf("expected generated/keep.txt to be re-included by .ctxconfig, got reason=%q", reason)
	}
}

func TestDumpHeuristicsRecognizeGeneratedMinifiedAndArtifacts(t *testing.T) {
	if !IsGeneratedText("// Code generated by tool. DO NOT EDIT.\npackage main\n") {
		t.Fatal("expected generated text marker to be recognized")
	}
	if !IsMinifiedText("bundle.min.js", strings.Repeat("var a=1;", 200), 1) {
		t.Fatal("expected minified file to be recognized")
	}
	if !IsLowValueArtifact("debug.log") || !IsLowValueArtifact(".gitkeep") {
		t.Fatal("expected low-value artifacts to be recognized")
	}
	if IsLowValueArtifact("Cargo.lock") {
		t.Fatal("did not expect Cargo.lock to be treated as low-value artifact")
	}
}

func writeFilterFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
